### ISSUE TITLE
Failing to send data

### ISSUE THREAD

**Issue by KHiis** [CESNET/pakiti-client#3]
Hi,

I encounter this issue when trying to send data to my server host.

> root@pakitibox:/tmp/pakiti-client/bin# perl pakiti-client --url="https://localhost/feed/"
> pakiti-client: failed to send data using /usr/bin/curl

> root@pakitibox:/tmp/pakiti-client/bin# which curl
> /usr/bin/curl

Any advice?

**Comment by kouril** [comment]
Hi,

please try running the client with the -d option, you should see the reason why curl is failing to send the data. Hope it helps and sorry for the delay,

Daniel

**Comment by tcatlas** [comment]
I am also having an issue sending data to pakiti-server.

pakiti-client with -d option:
https://i.imgur.com/EPZeLkO.png

pakiti-server apache2 `error.log` with `debug=true` in `Config.php`:
[error.log](https://github.com/CESNET/pakiti-client/files/2193043/error.log)

**Comment by kouril** [comment]
Could you please test the current version of the client?
