### ISSUE TITLE
Add an option to disable certificate verification

### ISSUE THREAD

**Issue by sbraz** [CESNET/pakiti-client#8]
Hi,
We're running pakiti on a local network where the server certificate is autosigned and therefore invalid. Would it be possible to add an option to disable certificate verification?
Currently, the `LWP::UserAgent` object always has verification enabled:
https://github.com/CESNET/pakiti-client/blob/383ee69939410cbc96902f4146f5a3c86dc7e219/pakiti-client#L391
I added this as a workaround but it would be better if it were disabled by default.
```perl
$ua->ssl_opts(verify_hostname => 0, SSL_verify_mode => 0x00);
```

**Comment by kouril** [comment]
I don't like much the change you're proposing, avoiding server checks isn't a good practise. I understand your situation though and propose to populate the clients with the (self-signed) server certificate (you can use the HTTPS_CA_DIR environment variable to specify an alternative directory with the cert).

**Comment by sbraz** [comment]
Yeah, I'm aware that it's not a good practise, I guess it's better to close this issue then.
